### ISSUE TITLE
Handling different dotnet version

### ISSUE THREAD

**Issue by jmauro** [chef-cookbooks/ms_dotnet45#3]
Hi,
Since different dotnet version are avalaible different cookbook has been created, I tried to merge all the "ms_dotnetX" cookbook into one (This would be easier for powershell cookbook and its dependency), I would be glad to have your input since I took the code from your cookbook ms_dotnet45: [Criteo Github](https://github.com/criteo-cookbooks/ms_dotnet)
Any comments or PR would be appreciated.

Regards,
JM

**Comment by tas50** [comment]
We've deprecated this cookbook in favor of the ms_dotnet cookbook, which offers a much better experience and support for all current .NET releases. Check that out if you still need this.
